<a href="https://colab.research.google.com/github/anustupdas/GoogleCollab-Computer-Vision-Tasks/blob/main/Train_Cartoon_Human_Face_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
!cp gdrive/MyDrive/dataset_main_Cartoon_human.zip Ultra-Light-Fast-Generic-Face-Detector-1MB/

In [ ]:
!python --version

Python 3.7.10


In [ ]:
!nvidia-smi

Mon Jun 14 06:58:54 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    23W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
!git clone https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB.git

Cloning into 'Ultra-Light-Fast-Generic-Face-Detector-1MB'...
remote: Enumerating objects: 902, done.
remote: Counting objects: 100% (88/88), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 902 (delta 19), reused 72 (delta 12), pack-reused 814
Receiving objects: 100% (902/902), 29.35 MiB | 3.72 MiB/s, done.
Resolving deltas: 100% (443/443), done.


In [ ]:
pwd

'/content'

In [ ]:
cd Ultra-Light-Fast-Generic-Face-Detector-1MB/

/content/Ultra-Light-Fast-Generic-Face-Detector-1MB


In [ ]:
!unzip dataset_main_Cartoon_human.zip

Streaming output truncated to the last 5000 lines.
  inflating: dataset/JPEGImages/personai_icartoonface_dettrain_68917.jpg  
  inflating: dataset/JPEGImages/personai_icartoonface_dettrain_68918.jpg  
  inflating: dataset/JPEGImages/personai_icartoonface_dettrain_68923.jpg  
  inflating: dataset/JPEGImages/personai_icartoonface_dettrain_68928.jpg  
  inflating: dataset/JPEGImages/personai_icartoonface_dettrain_68937.jpg  
  inflating: dataset/JPEGImages/personai_icartoonface_dettrain_68942.jpg  
  inflating: dataset/JPEGImages/personai_icartoonface_dettrain_68952.jpg  
  inflating: dataset/JPEGImages/personai_icartoonface_dettrain_69001.jpg  
  inflating: dataset/JPEGImages/personai_icartoonface_dettrain_69005.jpg  
  inflating: dataset/JPEGImages/personai_icartoonface_dettrain_69018.jpg  
  inflating: dataset/JPEGImages/personai_icartoonface_dettrain_69019.jpg  
  inflating: dataset/JPEGImages/personai_icartoonface_dettrain_69033.jpg  
 extracting: dataset/JPEGImages/personai_icartoon

In [ ]:
!unzip annotations.zip

Archive:  annotations.zip
   creating: annotations/
  inflating: annotations/0--Parade_0_Parade_marchingband_1_100.xml  
  inflating: annotations/0--Parade_0_Parade_marchingband_1_104.xml  
  inflating: annotations/0--Parade_0_Parade_marchingband_1_108.xml  
  inflating: annotations/0--Parade_0_Parade_marchingband_1_112.xml  
  inflating: annotations/0--Parade_0_Parade_marchingband_1_114.xml  
  inflating: annotations/0--Parade_0_Parade_marchingband_1_116.xml  
  inflating: annotations/0--Parade_0_Parade_marchingband_1_117.xml  
  inflating: annotations/0--Parade_0_Parade_marchingband_1_12.xml  
  inflating: annotations/0--Parade_0_Parade_marchingband_1_122.xml  
  inflating: annotations/0--Parade_0_Parade_marchingband_1_126.xml  
  inflating: annotations/0--Parade_0_Parade_marchingband_1_127.xml  
  inflating: annotations/0--Parade_0_Parade_marchingband_1_13.xml  
  inflating: annotations/0--Parade_0_Parade_marchingband_1_131.xml  
  inflating: annotations/0--Parade_0_Parade_marchingb

In [ ]:
!pip install torch==1.4.0


     |████████████████████████████████| 753.4MB 22kB/s 
ERROR: fastai 1.0.61 requires torchvision, which is not installed.
ERROR: torchtext 0.9.1 has requirement torch==1.8.1, but you'll have torch 1.4.0 which is incompatible.


In [ ]:
!pip install torchvision==0.5.0

     |████████████████████████████████| 4.0MB 11.9MB/s 


In [ ]:
!pip list

Package                       Version            
----------------------------- -------------------
absl-py                       0.12.0             
alabaster                     0.7.12             
albumentations                0.1.12             
altair                        4.1.0              
appdirs                       1.4.4              
argon2-cffi                   20.1.0             
arviz                         0.11.2             
astor                         0.8.1              
astropy                       4.2.1              
astunparse                    1.6.3              
async-generator               1.10               
atari-py                      0.2.9              
atomicwrites                  1.4.0              
attrs                         21.2.0             
audioread                     2.1.9              
autograd                      1.3                
Babel                         2.9.1              
backcall                      0.2.0              


In [ ]:
!cat Ultra-Light-Fast-Generic-Face-Detector-1MB/requirements.txt

numpy
torch
opencv_python
torchvision
typing
torchstat
torchsummary
ptflops
matplotlib
onnx
onnxruntime

In [ ]:
!pip install -r Ultra-Light-Fast-Generic-Face-Detector-1MB/requirements.txt

     |████████████████████████████████| 81kB 7.5MB/s 
     |████████████████████████████████| 12.2MB 19.0MB/s 
     |████████████████████████████████| 4.1MB 45.4MB/s 
  Created wheel for typing: filename=typing-3.7.4.3-cp37-none-any.whl size=26323 sha256=cff2a4fda85ef02b1e83b45b2852cceb7c6bd9ba0dfaec3010a0b33f9b7c2ade
  Stored in directory: /root/.cache/pip/wheels/2d/04/41/8e1836e79581989c22eebac3f4e70aaac9af07b0908da173be
  Created wheel for ptflops: filename=ptflops-0.6.5-cp37-none-any.whl size=8870 sha256=6f25393c61ff28c1e915fd380f76ca262fbe0b92bb93b69d7df9d53608c06b85
  Stored in directory: /root/.cache/pip/wheels/ef/ad/e9/892acc135cbdac3ba50eeb2d5912eedcf208215da54bd69e16
Successfully built typing ptflops


In [ ]:
!python train.py --datasets 'dataset' --validation_dataset 'dataset' --resume 'models/RFB-Epoch-5-Loss-4.pth'

priors nums:4420
/content/Ultra-Light-Fast-Generic-Face-Detector-1MB/vision/transforms/transforms.py:383: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/content/Ultra-Light-Fast-Generic-Face-Detector-1MB/vision/transforms/transforms.py:383: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/content/Ultra-Light-Fast-Generic-Face-Detector-1MB/vision/transforms/transforms.py:383: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tu

In [ ]:
cd Ultra-Light-Fast-Generic-Face-Detector-1MB/

/content/Ultra-Light-Fast-Generic-Face-Detector-1MB


In [ ]:
!zip weight_200_FACELITE_mix.zip models/*.*  

  adding: models/RFB-Epoch-0-Loss-7.747579288482666.pth (deflated 10%)
  adding: models/RFB-Epoch-100-Loss-4.525049781799316.pth (deflated 9%)
  adding: models/RFB-Epoch-105-Loss-4.527642154693604.pth (deflated 9%)
  adding: models/RFB-Epoch-10-Loss-4.7238969802856445.pth (deflated 9%)
  adding: models/RFB-Epoch-110-Loss-4.5326484680175785.pth (deflated 9%)
  adding: models/RFB-Epoch-115-Loss-4.542087459564209.pth (deflated 9%)
  adding: models/RFB-Epoch-15-Loss-5.099042797088623.pth (deflated 9%)
  adding: models/RFB-Epoch-20-Loss-4.461660385131836.pth (deflated 9%)
  adding: models/RFB-Epoch-25-Loss-4.355666065216065.pth (deflated 9%)
  adding: models/RFB-Epoch-30-Loss-4.2991029739379885.pth (deflated 9%)
  adding: models/RFB-Epoch-35-Loss-4.578226375579834.pth (deflated 9%)
  adding: models/RFB-Epoch-40-Loss-4.413667774200439.pth (deflated 9%)
  adding: models/RFB-Epoch-45-Loss-4.566915893554688.pth (deflated 9%)
  adding: models/RFB-Epoch-50-Loss-4.823343658447266.pth (deflated 10%

In [ ]:
!python train.py --datasets dataset/

usage: train.py [-h] [--dataset_type DATASET_TYPE]
                [--datasets DATASETS [DATASETS ...]]
                [--validation_dataset VALIDATION_DATASET] [--balance_data]
                [--net NET] [--freeze_base_net] [--freeze_net] [--lr LR]
                [--momentum MOMENTUM] [--weight_decay WEIGHT_DECAY]
                [--gamma GAMMA] [--base_net_lr BASE_NET_LR]
                [--extra_layers_lr EXTRA_LAYERS_LR] [--base_net BASE_NET]
                [--pretrained_ssd PRETRAINED_SSD] [--resume RESUME]
                [--scheduler SCHEDULER] [--milestones MILESTONES]
                [--t_max T_MAX] [--batch_size BATCH_SIZE]
                [--num_epochs NUM_EPOCHS] [--num_workers NUM_WORKERS]
                [--validation_epochs VALIDATION_EPOCHS]
                [--debug_steps DEBUG_STEPS] [--use_cuda USE_CUDA]
                [--checkpoint_folder CHECKPOINT_FOLDER] [--log_dir LOG_DIR]
                [--cuda_index CUDA_INDEX] [--power POWER]
                [--overlap_t

In [ ]:
pwd

'/content/Ultra-Light-Fast-Generic-Face-Detector-1MB'

In [ ]:
cd ..


/content/Ultra-Light-Fast-Generic-Face-Detector-1MB


In [ ]:
!unzip JPEGImages.zip

Archive:  JPEGImages.zip
  inflating: Anime_137.jpg           
  inflating: Anime_282.jpg           
  inflating: Anime_297.jpg           
 extracting: Anime_298.jpg           
  inflating: Anime_307.jpg           
 extracting: Anime_320.jpg           
  inflating: Anime_85.jpg            
  inflating: Anime_98.jpg            


In [ ]:
rm -rf detect_imgs_results/*.*

In [ ]:
!python detect_imgs.py --path 'Test_imgs'

priors nums:4420
          
Image:  Anime_85.jpg
Inference time:  0.015395
tensor([1])
label  tensor(1)
Found 1 faces. The output image is detect_imgs_results_new/
          
Image:  Messi.jpg
Inference time:  0.005869
tensor([1, 1])
label  tensor(1)
label  tensor(1)
Found 2 faces. The output image is detect_imgs_results_new/
          
Image:  Anime_282.jpg
Inference time:  0.006112
tensor([1])
label  tensor(1)
Found 1 faces. The output image is detect_imgs_results_new/
          
Image:  Anime_98.jpg
Inference time:  0.005456
tensor([1])
label  tensor(1)
Found 1 faces. The output image is detect_imgs_results_new/
          
Image:  2.jpg
Inference time:  0.00557
tensor([])
Found 0 faces. The output image is detect_imgs_results_new/
          
Image:  Anime_297.jpg
Inference time:  0.005645
tensor([1])
label  tensor(1)
Found 1 faces. The output image is detect_imgs_results_new/
          
Image:  Anime_320.jpg
Inference time:  0.006169
tensor([1])
label  tensor(1)
Found 1 faces. The o